### PR TITLE
[ja] Fix typos in Japanese content

### PR DESCRIPTION
**Pull request by otms61**
Thank you for the great project! I learned a lot and appreciate it!

I found some typos and duplicate sentences in Japanese content, so I fixed them.

### CODE REVIEW

**Comment by voluntas** [comment]
@otms61 I have checked the content. Thanks for the great fix. Can I have the conflicts fixed?

**Review by voluntas — APPROVED** [review]

**Comment by otms61** [comment]
@voluntas Thanks for the quick review!

The conflicts have already been resolved with [this commit](https://github.com/webrtc-for-the-curious/webrtc-for-the-curious/pull/153/commits/b0fadf8956a9358521be22fb348b49f77425b4cc), and I don't think there are any conflicts now.
Is there anything else I need to work on?

**Comment by voluntas** [comment]
@otms61 This repository can only be merged with git rebase, so it's probably https://github.com/webrtc-for-the-curious/webrtc-for-the-curious/pull/153/commits/b0fadf 8956a9358521be22fb348b49f77425b4cc It looks like you can't merge anymore because of this commit.

I don't usually use rebase, so I don't know how to fix this. Can you give me some good advice?

**Comment by otms61** [comment]
@voluntas  Oh, I'm very sorry. I followed Github's instructions for resolving conflicts in the GUI, but I guess that wasn't enough.

I was organizing my commits. Is this okay?

**Comment by voluntas** [comment]
@otms61 Thanks for the fix. Thank you very much for your help.

**Pull request merged**
