### PR TITLE
Fix sentence errors

### PR DESCRIPTION
**Pull request by hezhanbang**

### CODE REVIEW

**Review by mogren — APPROVED** [review]
Thanks, good catch! 🎉

**Comment by katepangLiu** [comment]
@hezhanbang @mogren
I think `The second function cooperates with the loss-based controller` should be right here, means `The second function  is the the delay-based controller, it cooperates with the loss-based controller` .

**Comment by mogren** [comment]
@katepangLiu, you are right. The sentence is still a bit confusing, maybe we could say this?
```
The delay-based controller cooperates with the loss-based controller, and looks at the variations in packet
arrival time.
```

**Comment by katepangLiu** [comment]
@mogren Yes, it seems better.

**Pull request merged**
