### PR TITLE
WIP - chapter: applied webrtc

### PR DESCRIPTION
**Pull request by leewardbound**
Seeking feedback on skeleton / layout

### CODE REVIEW

**Comment by Sean-Der** [comment]
This makes my day. The first time seeing new copy written by someone else :fire:

* I am going to avoid mentioning Pion (or any specific software or company). I want to make this is a place where companies/other projects feel comfortable recommending the book. 

Some more use cases! You can pull them from https://www.w3.org/TR/webrtc-nv-use-cases

* Teleoperation - Controlling Robots via DataChannel, streaming video
* Remote Control - Playing a video game or accessing a VNC server
* Conferencing (maybe this fits in your first one?)
* Broadcasting
* File Transfer
* Distributed CDN https://strivecast.com/p2p-sdk/
* IoT - Devices connect P2P inside your LAN and send around info. No need for a remote server

**Comment by Sean-Der** [comment]
I added you to the org, and feel free to merge stuff when still in a rough format!

**Comment by leewardbound** [comment]
Fantastic feedback thank you, I'll take a second pass tonight and merge to
master

**Comment by leewardbound** [comment]
Also I put this as chapter #99 until you assign me elsewhere @Sean-Der !

**Pull request merged**
