### PR TITLE
Update 02-signaling.md

### PR DESCRIPTION
**Pull request by Dw9**
add mid  description  
参考：https://datatracker.ietf.org/doc/html/rfc5888

### CODE REVIEW

**Review by katepangLiu — CHANGES_REQUESTED** [review]
Thanks @Dw9，可以考虑在英文版中也加入相应的描述。
The "mid" attribute is used for identifying media streams within a
   session description. 
https://datatracker.ietf.org/doc/html/rfc5888#section-4

**Comment by Dw9** [comment]
@katepangLiu 谢谢 已添加。

**Comment by katepangLiu** [comment]
Thansk, LGTM.

**Review by katepangLiu — APPROVED** [review]

**Comment by katepangLiu** [comment]
Hello @mogren  ,@hiroyuki-sato ,how about this one?
- Whether `mid` should be here or not?
- If so, how about cover other lang versions.

**Comment by hiroyuki-sato** [comment]
Basically LGTM 👍

I think it is a good idea to add the `mid` description into that part. 
And I think additional description help for this part.

For example, the `mid` uses combination with the `a=group` attribute. 

@mogren, @katepangLiu  What do you think?

**Comment by katepangLiu** [comment]
@hiroyuki-sato LGTM.

**Review by mogren — APPROVED** [review]
Thanks, `mid` was definitely missing. LGTM! 🚀

**Comment by hiroyuki-sato** [comment]
@mogren Thank you for your comment!
@katepangLiu Let's merge this PR. (Let's consider my comment in another PR.)

**Review by hiroyuki-sato — APPROVED** [review]

**Pull request merged**
