### PR TITLE
[ja] Catch up #237. Modify Allocation Trasnport description.

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
@voluntas Please take a look when you get to have time. This PR catch-up #237

### CODE REVIEW

**Comment by voluntas** [comment]
@hiroyuki-sato Thanks for the follow-up! LGTM

**Comment by hiroyuki-sato** [comment]
Thanks!

**Comment by mogren** [comment]
Btw, I did an attempt to generate a Japanese PDF, but getting CJK to work well with pandoc in a GitHub Action was really tricky. I managed to generate a PDF locally, on my Mac using:

```
pandoc --pdf-engine=xelatex -V CJKmainfont="Noto Sans JP" --resource-path=.:./content.ja:./content.ja/docs/images --toc -o test.pdf content.ja/_index.md content.ja/docs/*.md
```

But I just could not get that working in GitHub Actions. The changes I tried are available in https://github.com/mogren/webrtc-for-the-curious/blob/ja-pdf/.github/workflows/gh-pages.yml (with some commented out cruft as well.)

I might try some more later, I would really like to get it working for all our completed translations.

Here is the PDF I managed to generate, not sure if it even looks right: [webrtc-for-the-curious-ja.pdf](https://github.com/webrtc-for-the-curious/webrtc-for-the-curious/files/7782264/webrtc-for-the-curious-ja.pdf)

**Comment by hiroyuki-sato** [comment]
Hello, @mogren. Thank you for your great work! It seems that Japanese PDF generates good.
I also tried to generate a Japanese PDF too. (But It's not worked yet). So, your job is fantastic!

I just generate a cover page in Japanese. 😄 

epub-cover

**Comment by mogren** [comment]
@hiroyuki-sato Oh, awesome cover image! I tried to get the PDF to render a cover image as well, but that also turned out to be hard to get right. For the Japanese translation, please replace mine and Alex's names with yours and @voluntas.

I guess I could also just manually generate the japanese PDF for now and check it in to the repo so that we could link to it. 😄

**Comment by hiroyuki-sato** [comment]
Hello, @mogren.
We(me and @voluntas) discussed the cover image. We want to keep original authors and add new line 翻訳: 日本語翻訳チーム. 
It means "Translation: Japanese translation team.". I'll create a new PR/Issue later for that.
epub-cover

**Comment by mogren** [comment]
Awesome, thanks a lot! That, together with fixing #135 might be good enough for now.

**Pull request merged**
