### PR TITLE
add authors and translators to the cover page based on their contribution

### PR DESCRIPTION
**Pull request by zhuker**
Use blank cover
epub-cover notitle

and automatically generate authors
epub-cover

as well as add translators
epub-cover

### CODE REVIEW

**Comment by zhuker** [comment]
@CliffHan @katepangLiu  i used google translate to create the mandarin translations 
this is done only for example of how to automatically generate translated book cover, please fix my translations and layouts as you find fit

**Comment by zhuker** [comment]
@Sean-Der does this look ok?

**Comment by katepangLiu** [comment]
> @CliffHan @katepangLiu i used google translate to create the mandarin translations
> this is done only for example of how to automatically generate translated book cover, please fix my translations and layouts as you find fit

In my opinion, Title could be "献给好奇者的WebRTC". 
@CliffHan, How about this one.

**Comment by katepangLiu** [comment]
> > @CliffHan @katepangLiu i used google translate to create the mandarin translations
> > this is done only for example of how to automatically generate translated book cover, please fix my translations and layouts as you find fit
> 
> In my opinion, Title could be "献给好奇者的WebRTC".
> @CliffHan, How about this one.

@zhuker  And may I be there? Jajaja.

**Comment by zhuker** [comment]
> > > @CliffHan @katepangLiu i used google translate to create the mandarin translations
> > > this is done only for example of how to automatically generate translated book cover, please fix my translations and layouts as you find fit
> > 
> > In my opinion, Title could be "献给好奇者的WebRTC".
> > @CliffHan, How about this one.
> 
> @zhuker  And may I be there? Jajaja.

@katepangLiu feel free to modify make-cover-zh-cn.py to your liking I made it as just an example
Maybe put top 2 translators in a row?

**Comment by katepangLiu** [comment]
Haha, just kidding, I'm here for learning. You guys did a great job.

**Review by mogren — APPROVED** [review]
Thanks @zhuker, this is great! 

A small nit might be what size of cover image we should use? I know that Amazon recommends 2,560  x 1,600 pixels for epubs, which is huge. Not sure what the default PDF recommended size is.

**Comment by zhuker** [comment]
> Thanks @zhuker, this is great! 
> 
> A small nit might be what size of cover image we should use? I know that Amazon recommends 2,560  x 1,600 pixels for epubs, which is huge. Not sure what the default PDF recommended size is.

I just used what was there and created a cleaned up (aka "no text") version of it.
The resolution is 1400x2100 since it's portrait which is pretty close 
Do you think it should be 1600x2560?

**Comment by mogren** [comment]
I'm kind of surprised that Amazon want's such a high resolution, the one we currently have should be fine for now. I tried earlier to generate a cover page PDF, but for some reason I couldn't get pandoc to output it correctly. It was easier for the epub ones.

I think this PR looks great for now, thanks for adding this. (Next thing might be to auto-generate PDFs and epubs for the translated languages as well...)

**Comment by zhuker** [comment]
cc @voluntas @alishir do you want to add cover generators for your translations?

**Comment by zhuker** [comment]
@mogren i didnt realize you added sean as a reviewer before merging

**Comment by mogren** [comment]
No worries, that was just to give him a ping that you fixed the cover images. Thanks for merging it!

**Comment by voluntas** [comment]
@zhuker It's great! Could you please add a cover generator for Japanese as well?

**Pull request merged**
