### PR TITLE
FAQs chap translated to spanish

### PR DESCRIPTION
**Pull request by zackfall**
I just wanted to translate this chap first than the other ones

### CODE REVIEW

**Comment by mogren** [comment]
Possibly because we "Squash and merge" the changes into the repository. Have you set up this repo as upstream in git? If so, you should re-sync your fork of the repo. 

Something like `git fetch upstream && git rebase upstream/master`

**Comment by zackfall** [comment]
Hmm, just asking because I'm a noob with git, this is just when you have created another branch, right? And I don't really remember if I did set up the repo as a upstream, theres a way to confirm if the repo is upstream?

**Comment by hiroyuki-sato** [comment]
Hello, @zackfall 

Thank you for your contribution.

You can set up `upstream` like the following.

```
git remote add upstream https://github.com/webrtc-for-the-curious/webrtc-for-the-curious.git
```

After rebase, you can use a force option like `git push origin master -f`

**Comment by zackfall** [comment]
I think I did it, thanks, but now they all are unverified

**Review by hiroyuki-sato — APPROVED** [review]
LGTM 👍

**Review by mogren — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
