### PR TITLE
Sync chinese translation with english version at 2021/04/29.

### PR DESCRIPTION
**Pull request by CliffHan**

### CODE REVIEW

**Review by mogren — APPROVED** [review]
Thanks a lot for updating the text and image links!

It is possible that you'll have to copy the image folder as well to get the images to work correctly, similar to other translations: https://github.com/webrtc-for-the-curious/webrtc-for-the-curious/tree/master/content.ja/images

If you don't feel like adding that now, we can file a bug and address it in a later PR.

**Comment by CliffHan** [comment]
> Thanks a lot for updating the text and image links!
> 
> It is possible that you'll have to copy the image folder as well to get the images to work correctly, similar to other translations: https://github.com/webrtc-for-the-curious/webrtc-for-the-curious/tree/master/content.ja/images
> 
> If you don't feel like adding that now, we can file a bug and address it in a later PR.

I'm not very sure. I didn't copy the image folder because I changed image link in chinese document. For example, this line:
https://github.com/CliffHan/webrtc-for-the-curious/blame/sync-translation-cn-20210429/content.zh-cn/docs/07-data-communication.md#L363

I used "/images/07-connection-establishment.png" instead of original "../images/07-connection-establishment.png".

Do you think it's better to have another copy of image folder? If so, I'll just do that in next patch.

**Comment by mogren** [comment]
Using `/images` should work fine for the website, but won't work if we try to generate a PDF or epub using pandoc. It's fine to address that later, once we generate all the translations as well. 🙂

Feel free to merge this, thanks a lot!

**Comment by CliffHan** [comment]
> Using `/images` should work fine for the website, but won't work if we try to generate a PDF or epub using pandoc. It's fine to address that later, once we generate all the translations as well. 
> 
> Feel free to merge this, thanks a lot!

I see, I'll close this PR and give another one with images copied to content.zh-cn.
Thanks for pointing out this.

**Pull request closed without merging**
