### PR TITLE
Update index to make it work-in-progress

### PR DESCRIPTION
**Pull request by threeplanetssoftware**
Adds language to some key parts of the index to make it clear the book is a work in progress and desires help on GitHub.

### CODE REVIEW

**Comment by Sean-Der** [comment]
@threeplanetssoftware what do you think of  a dedicated `Work In Progress/Living Work` section?

I don't think it benefits the reader  to say 'we promise nothing' with every statement. I understand being frustrated that isn't complete yet. The reader instantly can tell that by opening the chapters.

**Comment by threeplanetssoftware** [comment]
That's fair and probably a better way to capture it. The other thing I was playing with but never found a good way to capture it was a table of the chapters, and rough "finishing". This would be a good place to solicit the different types of feedback you are looking for, whether small edits to clarify, or people will to jump in on larger bits.

For example, the fist three look fairly done and might solicit tweaks, the next two look partially done and might ask for people to submit PRs to finish, and then there is a long tail where you might have people drop their usernames to help claim ownership.

Example:

|Chapter|Status|Author|Need|
|-----------|----------|-------|----|
|1|90%|@Sean-Der|[Minor tweaks](https://github.com/webrtc-for-the-curious/webrtc-for-the-curious/issues/new)|
|2|90%|@Sean-Der|[Minor tweaks](https://github.com/webrtc-for-the-curious/webrtc-for-the-curious/issues/new)|
|5|10%|leewardbound|Consider volunteering to help [here](https://github.com/webrtc-for-the-curious/webrtc-for-the-curious/issues/10)|

Would you be amenable to that? Either way, I'll rework this to a work in progress section

**Comment by Sean-Der** [comment]
@threeplanetssoftware Oh yes that would be fantastic! I am 100% behind doing a table with Owner+Percentage. 

I have a bunch of 'ideas for improvement' I would put in the need section for the 90% chapters as well.

**Comment by threeplanetssoftware** [comment]
Ok, I looked at the table both on the index and on the README and thought it seemed more appropriate on the actual project README's contributing section. Easy enough to move if you'd prefer to see it in either the contributing chapter, or the index for the site. 

I started with percentages, but that seemed very subjective, so instead I tried to classify the stages as:
1. Unstarted (There's nothing really there but a thought)
2. Planning (There's a rough outline, still probably getting a feel for where it goes)
3. Authoring (Clearly content being written and maybe just some sections missing)
4. Finishing Touches (Lots of content, really looking at tiny things missing and clean up)

Please take a look and let me know what you think.

**Comment by Sean-Der** [comment]
I think this is perfect! I would love to merge as is @threeplanetssoftware, is that ok?

**Comment by threeplanetssoftware** [comment]
Absolutely!

**Comment by Sean-Der** [comment]
Merged with https://github.com/webrtc-for-the-curious/webrtc-for-the-curious/commit/c3b0b670d81e7bb81cd23a2aa9111a2a720072cf

Thank you so much for doing this! I really hope this gets more people involved.

**Pull request closed without merging**
