### PR TITLE
Update 12-glossary.md

### PR DESCRIPTION
**Pull request by szjoez**
fix typo

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
Hello, @szjoez 

Thank you for creating this PR. LGTM(I used Google Translate)

@katepangLiu 
I realized you were outside of the project member.
Did you leave this project?
I wanted to request a review of this PR.

**Comment by katepangLiu** [comment]
> @katepangLiu I realized you were outside of the project member. Did you leave this project? I wanted to request a review of this PR.
@hiroyuki-sato 
I'm sorry, I just reset my github account, can you invite me again？ 
Thanks.

**Comment by katepangLiu** [comment]
LGTM.

**Comment by hiroyuki-sato** [comment]
@katepangLiu Welcome back!

**Pull request merged**
